#!/bin/bash
#SBATCH --job-name=grpo_train
#SBATCH --output=logs/job_%j.out
#SBATCH --error=logs/job_%j.err
#SBATCH --time=08:00:00
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G

# Load modules
module purge
module load 2025
module load Python

# Go to your repo
cd /scratch/$USER/Teaching-Language-Models-to-Learn-from-Logical-Feedback

# Activate environment (adjust if needed)
source env/bin/activate

# Run training
python src/trainer.py \
  TRAINERS@trainer=tests/GRPO_test \
  MODELS@model=tests/qwen2.5_test